version: '3.4'

services:
  skillquiz1:
    image: skillquiz1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200
      - 8004:80
