version: '3.4'

services:
  skillquizfront:
    image: skillquizfront
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      PORT_API: ${PORT_API}
      URL_API: ${URL_API}
    ports:
      - "${PORT_FRONT}:80"
